--[[
                                                 2*                                                 
                                                M30                                                 
                                                8670                                                
                                                828*                                                
                                               O555WQ                                               
                                               7$C4hk                                               
                                               E#JCh0C                                              
                                              Y40SPMdC                                              
                                              PMCSQ0Zp                                              
                                             V83PJD2dTp                                             
                                            U8$JSF45Q0CJ                                            
                                           UE2BYOB0@*IJJO                                           
                                           M3BYVJ8Bo8QlTQ                                           
                                         SO0ATYOD4Wdqal1i0|                                         
                                        RL63TXRI80*dOOZ!O:LC                                        
                                       PPB7XVRKC5BopOLQZ02|0l                                       
                                     KOXKLWTSLE81WhqOLCLkFELdmJ                                     
                                   hFPXUWTTQLFA5$MkqOQCJJkLKqmawi                                   
                                 o0GINWUSTOKFB618*bwOQCJfJqFRdQp2ZQ                                 
                             Cdo@Wh$LQSWSNJFB71B#hpwOQLLCCJChKA8aa4MkZp                             
                          L0OZp#5AIRUVSPMJFB73@WakpwZO000000Q0aBNSQJFA40ko                          
                      QmQ1|ZB8BMUXXUSQNLIEA73$8*kdwmZZZZmmmmwqpbo2IUVXRC23FABw                      
              k2%qM0$mObW2BOXYYYWUSQNLJGD952@Wokpqwwwwqpdbbhao*#W%@026GNOSTQJCDIA0q8@q              
           pkhdLQmo4HORPNJHGFGHJJKJIGFCA63$8#hdpqwqqpdbho*M8%@$124566654456AFKOND0*db%B8a           
              iL|;:Il!If00wo272Wakbbbkkhhhkbdpqqqqpdbho#8B$24689BDEFGHHHLSQH4MWhO!!Qm|i             
                     I,,1Ifa5NFWbqmQJffJJCLQQOZmqpdka#W%$258BEHKMOOQQPJ6B098h!I                     
                          :i;ITppwOQLCT111TfJLQZmpbh*WB036ADILQUWWRLE84%oQ1                         
                             :i|::TZQdOQfTTTfJL0mpkoMB037BFJOUYXVSHCaZf:                            
                                 Il,|858dQJfJCQOwdh#8$37BFLQQTYYXEd1                                
                                   lTI!Z|fbbZOZmpkoW@26BHKGIROJC#l                                  
                                     IJ.|!;pJ2qqdh#%15BHFFP7o@bJ                                    
                                       ,JiLlp1ppkoW$4AHLTUkdf:                                      
                                        ITIQlfbqh*%19CPYCZmI                                        
                                         :Opwpqpo#839OYEML:                                         
                                           1Z00w8#W1IXG1Z.                                          
                                            lJi!oWW3Q9bmI                                           
                                            ;IQ:L8%F6JZ                                             
                                             ;iJ|k$N%m                                              
                                              ;dTw$Hkl                                              
                                               @o2401l                                              
                                               omoWI|                                               
                                               !QQk!O                                               
                                                md8Q                                                
                                                l#ah                                                
                                                 aaT                                                
                                                 !|
]]-- -- https://discord.gg/rZwbBMcD7G
local _fiEcFwN={{108,"cicoqRRY7T1oDpKpi6s3c3Hu3RdjPAZ1w7cJ/JjI7mN0ojtIR6wA7Wnnjgl6RULO9DpOPK6D+guXS0Fm3upqENdelD3kVEEXAcNKycafhl9aUNbbXKxwkYmXc7t157E65CahCdgrX6dfOtK1MtwEo0VKO1hsiYcn097GC6ZkOEm9bQiY6aXBqq7+olR/ZmuJBZWix5i3yRuqYxFk13oW754te2Bv35jCx8s73UiAv5YoOxqH4TJovV8ExhvKxzFwChCEBKK8WGI1qLHWqDCiSipvxiG53VukbX0="},{160,645549300,218},{176}};local _fmIgEtC=1;local _fsSeQfF={};local _fhTeWnI=23089;local _fcCfDqG=44220;local _flWbIxM=(_fhTeWnI+_fcCfDqG)%65521;_fhTeWnI=nil;_fcCfDqG=nil;local _fcSaVpX=0;local _ftJfJkA='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';local _faFvNtY={};for _fzHyUxU=1,#_ftJfJkA do _faFvNtY[string.byte(_ftJfJkA,_fzHyUxU)]=_fzHyUxU-1 end;local function _fpAzPlT(_fkGbHnO) local _fhXuTnY={};local _frLhChX=0;local _fqNcEyM=0;for _fzHyUxU=1,#_fkGbHnO do local _fyYtExE=string.byte(_fkGbHnO,_fzHyUxU);if _fyYtExE~=61 then local _q=_faFvNtY[_fyYtExE];if _q~=nil then _frLhChX=_frLhChX*64+_q;_fqNcEyM=_fqNcEyM+6;if _fqNcEyM>=8 then _fqNcEyM=_fqNcEyM-8;local _d=math.floor(_frLhChX/(2^_fqNcEyM))%256;_fhXuTnY[#_fhXuTnY+1]=_d;_frLhChX=_frLhChX%(2^_fqNcEyM) end end end end;return _fhXuTnY end;while _fmIgEtC<=#_fiEcFwN do local _fcItApC=_fiEcFwN[_fmIgEtC];local _fvDiUhM=_fcItApC[1];if _fvDiUhM==108 then local _ffGtGvA=_fpAzPlT(_fcItApC[2]);local _s={};for _i=1,#_ffGtGvA do _flWbIxM=(_flWbIxM*25173+13849)%65521;local _fqPlTmT=_flWbIxM%256;local _x=(_ffGtGvA[_i]-_fqPlTmT-(_fcSaVpX%251))%256;_fcSaVpX=_fcSaVpX+1;_s[#_s+1]=string.char(_x) end;_fsSeQfF[#_fsSeQfF+1]=table.concat(_s) elseif _fvDiUhM==160 then local _fvUnDlD=table.concat(_fsSeQfF);if #_fvUnDlD~=_fcItApC[3] then error('Flow VM: payload corrupto',0) end;local _fxSkVcI,_ftJrMqL=1,0;for _i=1,#_fvUnDlD do _fxSkVcI=(_fxSkVcI+string.byte(_fvUnDlD,_i))%65521;_ftJrMqL=(_ftJrMqL+_fxSkVcI)%65521 end;if (_ftJrMqL*65536+_fxSkVcI)~=_fcItApC[2] then error('Flow VM: integridad invalida',0) end;_fsSeQfF={_fvUnDlD} elseif _fvDiUhM==176 then local _fvUnDlD=table.concat(_fsSeQfF);local _foRsQlT,_fmSsLwG=loadstring(_fvUnDlD);if not _foRsQlT then error(_fmSsLwG,0) end;if setfenv and getfenv then pcall(setfenv,_foRsQlT,getfenv(1)) end;return _foRsQlT(...) else error('Flow VM: opcode invalido',0) end;_fmIgEtC=_fmIgEtC+1 end
